### ISSUE TITLE
Vincent se branle la Ptite Git

### ISSUE THREAD

**Issue by NathBo** [greglcr/PtiteGit#2]
Bonjour messieurs,

Vincent a le moins de lignes de code écrites parmi tous les contributeurs au repo !
C'est absolument inacceptable !
Je tiens à vous rappeler que la personne qui aura le moins de lignes écrites sera sacrifiée avec Clément sur l'autel de sacrifice du DI.

Sans menace,
Nathan

**Comment by vinc42** [comment]
Bonjour NathBo,

Il me semble que votre intervention n'est pas d'un très grand intérêt et au contraire nous fait perdre innutiliment notre temps.
Par ailleurs, la vulgarité de votre langage me sidère, je vous pris de vous montrer plus respectueux.

                                        Vincent,de l'équipe ptitGit
